version: "3.8"

services:
  queue:
    container_name: queue-service
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672 
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - smtp-service-network

networks:
  smtp-service-network:
    name: smtp-service
    driver: bridge